import localFont from "next/font/local";
import { Jost } from "next/font/google"; // Importing Jost font from Google Fonts
import "./globals.css";

const jost = Jost({
  // Adding Jost font with all weights
  subsets: ["latin"],
  weights: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={jost.className} // Including Jost font variable
      >
        {children}
      </body>
    </html>
  );
}
