"use client"

import { useState } from "react"
import { Plus, Minus } from "lucide-react"
import { motion, AnimatePresence } from "framer-motion"

export function FAQSection() {
  const [openItems, setOpenItems] = useState(new Set())

  const toggleItem = (index) => {
    setOpenItems((prev) => {
      const newSet = new Set(prev)
      if (newSet.has(index)) {
        newSet.delete(index)
      } else {
        newSet.add(index)
      }
      return newSet
    })
  }

  const handleKeyPress = (e, index) => {
    if (e.key === "Enter" || e.key === " ") {
      e.preventDefault()
      toggleItem(index)
    }
  }

  const faqs = [
    {
      question: "What is v0 exactly?",
      answer:
        "v0 is an AI-powered generative user interface system that helps you build React components using simple text prompts. It generates clean, production-ready code that you can copy and customize for your projects.",
    },
    {
      question: "Do I need to know Tailwind to use it?",
      answer:
        "While basic knowledge of Tailwind CSS is helpful, it's not required. v0 generates components with Tailwind classes, and you can learn as you go. The generated code is clean and well-structured, making it easy to understand and modify.",
    },
    {
      question: "Can I use these components commercially?",
      answer:
        "Yes! All components generated by v0 can be used in commercial projects. You own the code that's generated, and there are no licensing restrictions on using it in your applications.",
    },
    {
      question: "Are the components responsive and accessible?",
      answer:
        "Absolutely. v0 generates components that are responsive by default and follow accessibility best practices. All components include proper ARIA attributes, keyboard navigation, and semantic HTML structure.",
    },
    {
      question: "How do I integrate a component into my project?",
      answer:
        "Simply copy the generated code and paste it into your React project. v0 provides installation instructions for any required dependencies, and the components are designed to work seamlessly with modern React frameworks like Next.js.",
    },
  ]

  return (
    <section id="faq" className="relative overflow-hidden py-16 sm:py-20 md:py-24 lg:py-32">
      {/* Decorative background elements */}
      <div className="pointer-events-none absolute inset-0 z-0">
        <div className="absolute right-0 top-1/4 h-64 w-64 sm:h-96 sm:w-96 -translate-y-1/2 translate-x-1/2 rounded-full bg-primary/20 blur-3xl" />
        <div className="absolute left-0 top-3/4 h-64 w-64 sm:h-96 sm:w-96 -translate-x-1/2 -translate-y-1/2 rounded-full bg-primary/15 blur-3xl" />
      </div>

      <div className="container relative z-10 mx-auto px-4 sm:px-6 lg:px-8">
        {/* Section badge */}
        <motion.div
          className="flex justify-center"
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
          viewport={{ once: true, margin: "-100px" }}
        >
          <div className="inline-flex items-center gap-2 rounded-full border border-primary/40 bg-primary/5 px-3 sm:px-4 py-1.5 text-xs sm:text-sm font-medium uppercase tracking-wide text-primary backdrop-blur-sm">
            <span className="text-sm sm:text-base" aria-hidden="true">✶</span>
            <span>FAQs</span>
          </div>
        </motion.div>

        {/* Section heading */}
        <motion.h2
          className="mx-auto mt-4 sm:mt-6 max-w-2xl text-center text-3xl sm:text-4xl md:text-5xl lg:text-6xl font-semibold tracking-tight lg:leading-tight px-4"
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, delay: 0.1 }}
          viewport={{ once: true, margin: "-100px" }}
        >
          Questions? We've got{" "}
          <span className="bg-gradient-to-b from-foreground via-rose-200 to-primary bg-clip-text text-transparent">
            answers
          </span>
        </motion.h2>

        {/* FAQ items */}
        <div className="mx-auto mt-12 sm:mt-16 max-w-3xl">
          <div className="space-y-4">
            {faqs.map((faq, index) => {
              const isOpen = openItems.has(index)
              
              return (
                <motion.div
                  key={index}
                  className="group rounded-2xl border border-white/10 bg-gradient-to-b from-secondary/40 to-secondary/10 shadow-[0px_2px_0px_0px_rgba(255,255,255,0.1)_inset] transition-all duration-300 hover:border-white/20 hover:shadow-lg"
                  initial={{ opacity: 0, y: 20 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.4, delay: index * 0.08 }}
                  viewport={{ once: true, margin: "-50px" }}
                >
                  <button
                    className="flex w-full items-start justify-between gap-4 p-6 text-left transition-colors focus:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2 focus-visible:ring-offset-background"
                    onClick={() => toggleItem(index)}
                    onKeyDown={(e) => handleKeyPress(e, index)}
                    aria-expanded={isOpen}
                    aria-controls={`faq-answer-${index}`}
                  >
                    <h3 className="flex-1 text-lg font-semibold leading-tight sm:text-xl">
                      {faq.question}
                    </h3>
                    
                    <motion.div
                      animate={{ rotate: isOpen ? 180 : 0 }}
                      transition={{ duration: 0.3, ease: [0.4, 0, 0.2, 1] }}
                      className="flex-shrink-0 text-primary"
                    >
                      {isOpen ? (
                        <Minus className="h-6 w-6" strokeWidth={2.5} />
                      ) : (
                        <Plus className="h-6 w-6" strokeWidth={2.5} />
                      )}
                    </motion.div>
                  </button>

                  <AnimatePresence initial={false}>
                    {isOpen && (
                      <motion.div
                        id={`faq-answer-${index}`}
                        initial={{ height: 0, opacity: 0 }}
                        animate={{ 
                          height: "auto", 
                          opacity: 1,
                          transition: {
                            height: { duration: 0.3, ease: [0.4, 0, 0.2, 1] },
                            opacity: { duration: 0.25, delay: 0.05 }
                          }
                        }}
                        exit={{ 
                          height: 0, 
                          opacity: 0,
                          transition: {
                            height: { duration: 0.3, ease: [0.4, 0, 0.2, 1] },
                            opacity: { duration: 0.2 }
                          }
                        }}
                        className="overflow-hidden"
                      >
                        <div className="px-6 pb-6 pt-0">
                          <p className="text-base leading-relaxed text-muted-foreground sm:text-lg">
                            {faq.answer}
                          </p>
                        </div>
                      </motion.div>
                    )}
                  </AnimatePresence>
                </motion.div>
              )
            })}
          </div>
        </div>
      </div>
    </section>
  )
}